typography_spectrum: 0.70654
color:
  brandColors:
    - '#e5e4e0'
    - '#424d45'
    - '#b9b2a9'
    - '#938269'
    - '#121318'
  brandStrength: 0.375
  lightness: 0.375
  saturation: 0.75
  rhythmicContrast: 0.75
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.48517
analytics:
  google: null
  facebook: null
  twitter: null
name: Sonas Jacks
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Woodworking
description: easy to fall in love with
purpose: []
