name: Sonas Jacks
favicon: null
layout_spectrum: 0.48517
typography_spectrum: 0.70654
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e5e4e0'
    - '#424d45'
    - '#b9b2a9'
    - '#938269'
    - '#121318'
  brandStrength: 0.375
  lightness: 0.5
  saturation: 0.3125
  rhythmicContrast: 1
purpose: []
