name: Sonas Jacks
favicon: null
layout_spectrum: 0.01939557958394289
typography_spectrum: 0.6359689079690725
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e5e4e0'
    - '#424d45'
    - '#b9b2a9'
    - '#938269'
    - '#121318'
  brandStrength: 0.75
  lightness: 0.35479751299135387
  saturation: 0.44250488630495965
  rhythmicContrast: 0.9906534892506897
purpose: []
